PROJNAME=Thesis_Master
DEVICE=CY8C28433
BASEDEVICE=CY8C28033
PROJPATH=C:/Users/Admin/DOCUME~1/PSOCDE~1.0PR/THC055~1/THESIS~1
PSOCDIR=C:/PROGRA~1/Cypress/Common/CYPRES~3
INCLUDE_PATH=C:/PROGRA~1/Cypress/Common/CYPRES~3/tools/include/CY60D2~1
CSRCS= main.c
LIBCSRCS=
ASMSRCS=
LIBASMSRCS= comp_serial.asm comp_serialint.asm comp_serialplus.asm psocconfig.asm psocconfigtbl.asm psocdynamic.asm psocdynamicint.asm receive.asm receiveint.asm receiveplus.asm rx_timeout.asm rx_timeoutint.asm transmit.asm transmitint.asm transmitplus.asm tx_repeater.asm tx_repeaterint.asm tx_repeaterplus.asm tx_timeout.asm tx_timeoutint.asm
OBJECT_SOURCES= main.c
FILLVALUE=0x30
LASTROM=0x3fff
LASTRAM=0x3ff
LAST_DATARAM=0x2ff
CODECOMPRESSOR=
MORE_CFLAGS=-Wf-nomac -Wf-Osize -Wf-LMM4 -D_LMM
RELSTART=0x190
CDEFINES=
LIBS=
UMLIBS=
LIB_PATH=
ENABLE_ALIGN_SHIFT=0
LMM=1
SYS_INC_CONTENTS:=SYSTEM_STACK_PAGE:_equ_3 SYSTEM_STACK_BASE_ADDR:_equ_0h SYSTEM_LARGE_MEMORY_MODEL:_equ_1 SYSTEM_SMALL_MEMORY_MODEL:_equ_0 IMAGECRAFT:_equ_1 HITECH:_equ_2 TOOLCHAIN:_equ_IMAGECRAFT 
SYSTEM_TOOLS=1
CSFLOW=
CONFIG_NAMES=transmitter_config pc_listener receiver_config transmitter_config pc_listener receiver_config transmitter_config pc_listener receiver_config transmitter_config pc_listener receiver_config transmitter_config pc_listener receiver_config transmitter_config pc_listener receiver_config transmitter_config pc_listener receiver_config transmitter_config pc_listener receiver_config transmitter_config pc_listener receiver_config transmitter_config pc_listener receiver_config transmitter_config pc_listener receiver_config 
