/******************************************************************************
*  Generated by PSoC Designer 5.0.985.0
******************************************************************************/
#include "COMP_SERIAL.h"
#include "TX_REPEATER.h"
#include "RECEIVE.h"
#include "RX_TIMEOUT.h"
#include "TRANSMIT.h"
#include "TX_TIMEOUT.h"
