/******************************************************************************
*  Generated by PSoC Designer 5.0.985.0
******************************************************************************/
extern void LoadConfig_transmitter_config( void);
extern void ReloadConfig_transmitter_config( void);
extern void UnloadConfig_transmitter_config( void);
extern char Istransmitter_configLoaded( void);
extern void LoadConfig_pc_listener( void);
extern void UnloadConfig_pc_listener( void);
extern char Ispc_listenerLoaded( void);
extern void LoadConfig_receiver_config( void);
extern void UnloadConfig_receiver_config( void);
extern char Isreceiver_configLoaded( void);
extern void UnloadConfig_Total( void);
