//*****************************************************************************
//*****************************************************************************
//  FILENAME: RECEIVE.h
//   Version: 3.3, Updated on 2009/7/10 at 10:46:15
//  Generated by PSoC Designer 5.0.985.0
//
//  DESCRIPTION:  RX8 User Module C Language interface file for the
//                22/24/25/26/27xxx PSoC family of devices.
//-----------------------------------------------------------------------------
//      Copyright (c) Cypress MicroSystems 2000-2003. All Rights Reserved.
//*****************************************************************************
//*****************************************************************************


// include the global header file
#include <m8c.h>

#define RECEIVE_RXBUF_ENABLE 1

//-------------------------------------------------
// Prototypes of the RECEIVE API.
//-------------------------------------------------

#if ( RECEIVE_RXBUF_ENABLE )
extern char RECEIVE_aRxBuffer[];
extern BYTE RECEIVE_bRxCnt;
extern BYTE RECEIVE_fStatus;
#endif

// Create pragmas to support proper argument and return value passing
#pragma fastcall16  RECEIVE_EnableInt
#pragma fastcall16  RECEIVE_DisableInt
#pragma fastcall16  RECEIVE_Start
#pragma fastcall16  RECEIVE_Stop
#pragma fastcall16  RECEIVE_bReadRxData
#pragma fastcall16  RECEIVE_bReadRxStatus

#pragma fastcall16  RECEIVE_cGetChar
#pragma fastcall16  RECEIVE_cReadChar
#pragma fastcall16  RECEIVE_iReadChar

#if ( RECEIVE_RXBUF_ENABLE )
#pragma fastcall16  RECEIVE_CmdReset
#pragma fastcall16  RECEIVE_bCmdCheck
#pragma fastcall16  RECEIVE_bErrCheck
#pragma fastcall16  RECEIVE_bCmdLength
#pragma fastcall16  RECEIVE_szGetParam
#pragma fastcall16  RECEIVE_szGetRestOfParams
#endif

//-------------------------------------------------
// Prototypes of the RECEIVE API.
//-------------------------------------------------
extern void  RECEIVE_EnableInt(void);
extern void  RECEIVE_DisableInt(void);
extern void  RECEIVE_Start(BYTE bParity);
extern void  RECEIVE_Stop(void);
extern BYTE  RECEIVE_bReadRxData(void);
extern BYTE  RECEIVE_bReadRxStatus(void);

// High level RX functions
extern CHAR         RECEIVE_cGetChar(void);
extern CHAR         RECEIVE_cReadChar(void);
extern INT          RECEIVE_iReadChar(void);

#if ( RECEIVE_RXBUF_ENABLE )
extern void   RECEIVE_CmdReset(void);
extern BYTE   RECEIVE_bCmdCheck(void);
extern BYTE   RECEIVE_bErrCheck(void);
extern BYTE   RECEIVE_bCmdLength(void);
extern char * RECEIVE_szGetParam(void);
extern char * RECEIVE_szGetRestOfParams(void);
#endif

// Old function call names, do not use.
// These names will be removed in a future release.
#pragma fastcall16 bRECEIVE_ReadRxData
#pragma fastcall16 bRECEIVE_ReadRxStatus
extern BYTE bRECEIVE_ReadRxData(void);
extern BYTE bRECEIVE_ReadRxStatus(void);

//-------------------------------------------------
// Constants for RECEIVE API's.
//-------------------------------------------------

//------------------------------------
// Receiver Interrupt masks
//------------------------------------
#define RECEIVE_INT_REG_ADDR                   ( 0x0e1 )
#define RECEIVE_bINT_MASK                      ( 0x04 )

//------------------------------------
// Receiver Parity masks
//------------------------------------
#define  RECEIVE_PARITY_NONE         0x00
#define  RECEIVE_PARITY_EVEN         0x02
#define  RECEIVE_PARITY_ODD          0x06

//------------------------------------
//  Receiver Status Register masks
//------------------------------------
#define  RECEIVE_RX_ACTIVE           0x10
#define  RECEIVE_RX_COMPLETE         0x08
#define  RECEIVE_RX_PARITY_ERROR     0x80
#define  RECEIVE_RX_OVERRUN_ERROR    0x40
#define  RECEIVE_RX_FRAMING_ERROR    0x20
#define  RECEIVE_RX_NO_ERROR         0xE0

#define  RECEIVE_RX_NO_DATA         0x01

#define  RECEIVE_RX_BUF_ERROR             0xF0  // Mask for any Rx that may occur.
#define  RECEIVE_RX_BUF_OVERRUN           0x10  // This indicates the software buffer has
                                                           // been over run.
#define  RECEIVE_RX_BUF_CMDTERM           0x01  // Command terminator has been received.

// Old defines, will be removed in future release
#define  RX8_PARITY_NONE         0x00
#define  RX8_PARITY_EVEN         0x02
#define  RX8_PARITY_ODD          0x06
#define  RX8_RX_ACTIVE           0x10
#define  RX8_RX_COMPLETE         0x08
#define  RX8_RX_PARITY_ERROR     0x80
#define  RX8_RX_OVERRUN_ERROR    0x40
#define  RX8_RX_FRAMING_ERROR    0x20
#define  RX8_RX_NO_ERROR         0xE0

//-------------------------------------------------
// Register Addresses for RECEIVE
//-------------------------------------------------
#pragma ioport  RECEIVE_CONTROL_REG:    0x02b              // Control register
BYTE            RECEIVE_CONTROL_REG;
#pragma ioport  RECEIVE_RX_SHIFT_REG:   0x028              // RX Shift Register register
BYTE            RECEIVE_RX_SHIFT_REG;
#pragma ioport  RECEIVE_RX_BUFFER_REG:  0x02a              // RX Buffer Register
BYTE            RECEIVE_RX_BUFFER_REG;
#pragma ioport  RECEIVE_FUNC_REG:   0x128                  // Function register
BYTE            RECEIVE_FUNC_REG;
#pragma ioport  RECEIVE_INPUT_REG:  0x129                  // Input register
BYTE            RECEIVE_INPUT_REG;
#pragma ioport  RECEIVE_OUTPUT_REG: 0x12a                  // Output register
BYTE            RECEIVE_OUTPUT_REG;

// end of file RECEIVE.h

